### Get All Contacts
GET http://localhost:3000/contacts

### Get Contact by ID - Precious Aaron
GET http://localhost:3000/contacts/67cc98aabe1ebd2297eca158

### Get Contact by ID - Adebayo Oluwaseun
GET http://localhost:3000/contacts/67d0ae1ab81e42f9ae6ac5ab

### Get Contact by ID - Zainab Abdullahi
GET http://localhost:3000/contacts/67d0ae6eb81e42f9ae6ac5ad

### Get Contact by ID - Tunde Akinwale
GET http://localhost:3000/contacts/67d0ae91b81e42f9ae6ac5ae

### Create New Contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "favoriteColor": "Blue",
    "birthday": "2000-01-01"
}

### Update Contact - Precious Aaron
PUT http://localhost:3000/contacts/67cc98aabe1ebd2297eca158
Content-Type: application/json

{
    "firstName": "Precious",
    "lastName": "Aaron Updated",
    "email": "precious.aaron@gmail.com",
    "favoriteColor": "Red",
    "birthday": "1990-05-05"
}

### Delete Contact - Tunde Akinwale
DELETE http://localhost:3000/contacts/67d0ae91b81e42f9ae6ac5ae
